#!/usr/bin/env node
/**
 * Reads intrinsic sizes for public/images raster files and writes src/data/imageSizes.ts.
 * Run after adding or replacing images: npm run measure-images
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, '..');
const imagesRoot = path.join(rootDir, 'public/images');
const outFile = path.join(rootDir, 'src/data/imageSizes.ts');

function pngSize(buf) {
	if (buf[0] !== 0x89 || buf[1] !== 0x50) return null;
	return { width: buf.readUInt32BE(16), height: buf.readUInt32BE(20) };
}

function jpegSize(buf) {
	if (buf[0] !== 0xff || buf[1] !== 0xd8) return null;
	let i = 2;
	while (i < buf.length) {
		if (buf[i] !== 0xff) {
			i++;
			continue;
		}
		const marker = buf[i + 1];
		if (marker === 0xc0 || marker === 0xc1 || marker === 0xc2) {
			return { height: buf.readUInt16BE(i + 5), width: buf.readUInt16BE(i + 7) };
		}
		if (
			marker === 0xd8 ||
			marker === 0xd9 ||
			marker === 0x01 ||
			(marker >= 0xd0 && marker <= 0xd7)
		) {
			i += 2;
			continue;
		}
		const len = buf.readUInt16BE(i + 2);
		i += 2 + len;
	}
	return null;
}

function webpSize(buf) {
	if (buf.toString('ascii', 0, 4) !== 'RIFF' || buf.toString('ascii', 8, 12) !== 'WEBP') {
		return null;
	}
	const type = buf.toString('ascii', 12, 16);
	if (type === 'VP8 ') {
		return {
			width: buf.readUInt16LE(26) & 0x3fff,
			height: buf.readUInt16LE(28) & 0x3fff,
		};
	}
	if (type === 'VP8L') {
		const bits = buf.readUInt32LE(21);
		return {
			width: (bits & 0x3fff) + 1,
			height: ((bits >> 14) & 0x3fff) + 1,
		};
	}
	if (type === 'VP8X') {
		return {
			width: 1 + buf[24] + (buf[25] << 8) + (buf[26] << 16),
			height: 1 + buf[27] + (buf[28] << 8) + (buf[29] << 16),
		};
	}
	return null;
}

function walk(dir, rel = '') {
	/** @type {Record<string, [number, number]>} */
	const out = {};
	for (const ent of fs.readdirSync(dir, { withFileTypes: true })) {
		const abs = path.join(dir, ent.name);
		const nextRel = rel ? `${rel}/${ent.name}` : ent.name;
		if (ent.isDirectory()) {
			Object.assign(out, walk(abs, nextRel));
			continue;
		}
		if (!/\.(png|jpe?g|webp)$/i.test(ent.name)) continue;
		const buf = fs.readFileSync(abs);
		const size = pngSize(buf) || jpegSize(buf) || webpSize(buf);
		if (!size) {
			console.error(`Could not read size: ${nextRel}`);
			continue;
		}
		out[nextRel] = [size.width, size.height];
	}
	return out;
}

if (!fs.existsSync(imagesRoot)) {
	console.error(`Missing images directory: ${imagesRoot}`);
	process.exit(1);
}

const sizes = walk(imagesRoot);
const keys = Object.keys(sizes).sort();
const lines = [
	'// Auto-generated by scripts/measure-images.mjs. Do not edit by hand.',
	'// Run `npm run measure-images` after adding or replacing images under public/images.',
	'',
	'export type ImageSize = readonly [width: number, height: number];',
	'',
	'/** Intrinsic pixel sizes for raster files under public/images/. */',
	'export const imageSizes: Record<string, ImageSize> = {',
	...keys.map((key) => `\t${JSON.stringify(key)}: [${sizes[key][0]}, ${sizes[key][1]}],`),
	'};',
	'',
];

fs.writeFileSync(outFile, lines.join('\n'));
console.log(`Wrote ${keys.length} sizes to ${path.relative(rootDir, outFile)}`);
